name: archethic
base: core20
summary: Official ArchEthic blockchain node software
description: |
  Welcome to ArchEthic blockchain. This tool enables you to install and run an ArchEthic node. ArchEthic is a next generation of blockchain focused on rapid scalability and easy accessibility.
    
  ArchEthic features:

    Fast transaction processing (> 1M tps)

    Lower energy consumption than other blockchain

    Designed with a high level of security (ARCH consensus supporting 90% of maliciousness)

    Adaptive cryptographic algorithms (quantum resistant)

    Decentralised Identity and Self Sovereign Identity

    Smart contract platform powered by a built-in interpreter

    Strong scalability with geo secured sharding

    Soft-Real-Time P2P view with supervised networking


  Maintained by:

    ArchEthic Foundation
    https://www.archethic.net
grade: stable
confinement: strict # use 'strict' once you have the right plugs and slots
adopt-info: archethic-node
architectures:
  - build-on: amd64
    run-on: amd64

package-repositories:
  - type: apt
    formats: [deb]
    components: [contrib]
    suites: [focal]
    key-id: 434975BD900CCBE4F7EE1B1ED208507CA14F4FCA
    url: https://packages.erlang-solutions.com/ubuntu

apps:
  archethic-node:
    daemon: simple
    command-chain:
      - bin/set-config
    command: bin/archethic_node_start
    stop-command: bin/archethic_node_stop
    install-mode: disable
    refresh-mode: endure
    plugs:
      - network
      - network-bind
      - tpm

layout:
  /usr/lib/locale:
    bind: $SNAP_COMMON/usr/lib/locale
  /usr/share/i18n/SUPPORTED:
    symlink: $SNAP/usr/share/i18n/SUPPORTED
  /usr/share/i18n/locales:
    symlink: $SNAP/usr/share/i18n/locales
  /usr/share/i18n/charmaps:
    symlink: $SNAP/usr/share/i18n/charmaps

parts:
  archethic-node:
    plugin: dump
    source: https://github.com/archethic-foundation/archethic-node.git
    source-branch: 'master'
    source-type: git
    build-packages:
      - locales
      - gnupg2
      - build-essential
      - zlib1g-dev
      - libgmp-dev
      - nodejs
      - npm
      - openssl
      - libsodium23
      - libsodium-dev
      - autoconf-archive
      - libcmocka0
      - libcmocka-dev
      - procps
      - pkg-config
      - gcc
      - libtool
      - automake
      - libssl-dev
      - uthash-dev
      - autoconf
      - doxygen
      - libjson-c-dev
      - libini-config-dev
      - libcurl4-openssl-dev
      - acl
      - git
      - wget
      - esl-erlang
      - elixir
    build-environment:
      - DEBIAN_FRONTEND: 'noninteractive'
      - LANG: 'en_US.UTF-8'
      - MIX_ENV: 'prod'
      - MIX_HOME: '/root/.mix'
      - CFLAGS: ''
      - CPPFLAGS: ''
      - CXXFLAGS: ''
      - LDFLAGS: ''
      - PKG_CONFIG_PATH: ''
    stage-packages:
      - locales
      - esl-erlang
      - elixir
      - openssl
      - libsodium23
      - tpm2-tools 
      - libwxgtk-webview3.0-gtk3-0v5
      - libglu1-mesa
      - unixodbc-dev 
    override-build: |
      VERSION=$(grep 'version:' mix.exs | cut -d '"' -f2)
      snapcraftctl set-version $VERSION
      locale-gen en_US.UTF-8
      update-locale LC_ALL=en_US.UTF-8
      wget https://github.com/tpm2-software/tpm2-tss/releases/download/3.1.0/tpm2-tss-3.1.0.tar.gz
      tar -xf tpm2-tss-3.1.0.tar.gz --one-top-level=tpm2-tss --strip-components 1
      cd tpm2-tss
      ./configure --with-udevrulesdir=/etc/udev/rules.d
      make -j$(nproc) 
      make install
      sed -i "s/tss/$(whoami)/gi" /etc/udev/rules.d/tpm-udev.rules
      udevadm control --reload-rules
      udevadm trigger
      ldconfig
      apt install -y tpm2-tools
      cd -
      make
      mix local.hex --if-missing --force &
      wait $!
      mix local.rebar --if-missing --force &
      wait $!
      mix deps.get &
      wait $!
      cd assets
      npm install
      npm ci
      npm run deploy
      cd -
      mix phx.digest &
      wait $!
      mix distillery.release &
      wait $!
      tar zxvf _build/prod/rel/archethic_node/releases/$VERSION/archethic_node.tar.gz -C $SNAPCRAFT_PART_INSTALL/
      rm -rf _build/prod
      mix distillery.release --upgrade &
      wait $!
      cp _build/prod/rel/archethic_node/releases/$VERSION/archethic_node.tar.gz $SNAPCRAFT_PART_INSTALL/releases/$VERSION/archethic_node.tar.gz
      echo $VERSION >$SNAPCRAFT_PART_INSTALL/VERSION
      echo '#!/bin/bash' >$SNAPCRAFT_PART_INSTALL/bin/archethic_node_start
      echo '' >>$SNAPCRAFT_PART_INSTALL/bin/archethic_node_start
      echo 'cd $SNAP_COMMON' >>$SNAPCRAFT_PART_INSTALL/bin/archethic_node_start
      echo 'bin/archethic_node foreground' >>$SNAPCRAFT_PART_INSTALL/bin/archethic_node_start
      echo 'exec "$@"' >>$SNAPCRAFT_PART_INSTALL/bin/archethic_node_start
      chmod +x $SNAPCRAFT_PART_INSTALL/bin/archethic_node_start
      echo '#!/bin/bash' >$SNAPCRAFT_PART_INSTALL/bin/archethic_node_stop
      echo '' >>$SNAPCRAFT_PART_INSTALL/bin/archethic_node_stop
      echo 'cd $SNAP_COMMON' >>$SNAPCRAFT_PART_INSTALL/bin/archethic_node_stop
      echo 'bin/archethic_node stop' >>$SNAPCRAFT_PART_INSTALL/bin/archethic_node_stop
      echo 'exec "$@"' >>$SNAPCRAFT_PART_INSTALL/bin/archethic_node_stop
      chmod +x $SNAPCRAFT_PART_INSTALL/bin/archethic_node_stop
      cp -p $SNAPCRAFT_PROJECT_DIR/snap/local/set-config $SNAPCRAFT_PART_INSTALL/bin/
