name: publish-mainnet-track
on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - uses: snapcore/action-build@v1
        id: build
      - uses: snapcore/action-publish@v1
        with:
            store_login: ${{ secrets.SNAP_TOKEN }}
            snap: ${{ steps.build.outputs.snap }}
            release: mainnet/edge
