#!/bin/sh

update-java-alternatives --jre-headless -s java-1.8.0-openjdk-amd64

scylla_setup --no-raid-setup --no-ec2-check --no-kernel-check --no-verify-package --no-sysconfig-setup --io-setup=1 --no-version-check --no-cpuscaling-setup --no-fstrim-setup --no-memory-setup --no-swap-setup

scylla_memory_setup --memory=8G
scylla_cpuset_setup --cpuset 2

systemctl start scylla-server

sh -c 'cat > /etc/default/archethic.env' << EOF

    ARCHETHIC_P2P_BOOTSTRAPPING_SEEDS=
    ARCHETHIC_CRYPTO_SEED=
    ARCHETHIC_NETWORK_TYPE=testnet
    ARCHETHIC_CRYPTO_NODE_KEYSTORE_IMPL=SOFTWARE
    ARCHETHIC_NODE_ALLOWED_KEY_ORIGINS=SOFTWARE
    ARCHETHIC_BEACON_CHAIN_SLOT_TIMER_INTERVAL="*/10 * * * * *"
    ARCHETHIC_BEACON_CHAIN_SUMMARY_TIMER_INTERVAL="0 * * * * *"
    ARCHETHIC_ORACLE_CHAIN_POLLING_INTERVAL="*/10 * * * * *"
    ARCHETHIC_ORACLE_CHAIN_SUMMARY_INTERVAL="50 * * * * *"
    ARCHETHIC_SHARED_SECRETS_RENEWAL_SCHEDULER_INTERVAL="40 * * * * * *"
    ARCHETHIC_SHARED_SECRETS_APPLICATION_INTERVAL="0 * * * * * *"
    ARCHETHIC_SELF_REPAIR_SCHEDULER_INTRERVAL="5 * * * * * *"
    ARCHETHIC_REWARD_SCHEDULER_INTERVAL="30 * * * * *"
EOF

sh -c 'cat > /etc/systemd/system/archethic.service' << EOF

    [Unit]
    Description=ARCHEthic service
    After=local-fs.target network.target

    [Service]
    Type=simple
    User=$USER
    Group=$USER

    WorkingDirectory=$SNAP

    ExecStart=$SNAP/bin/archethic_node foreground
    ExecStop=$SNAP/bin/archethic_node stop

    EnvironmentFile=/etc/default/archethic.env
    Environment=LANG=en_US.utf8
    Environment=MIX_ENV=prod
    Environment=ERLANG_COOKIE=$ERLANG_COOKIE

    Restart=on-failure
    RemainAfterExit=yes
    RestartSec=5

    LimitNOFILE=65535
    UMask=0027
    SyslogIdentifier=archethic

    [Install]
    WantedBy=multi-user.target
EOF

systemctl daemon-reload
systemctl enable archethic
systemctl start archethic
